INPUTDIR=
OUTPUTDIR=
cd $INPUTDIR
for f in *R1*.fastq.gz
do
BASENAME=$(basename "$f" _R1_001.fastq.gz)
cutadapt -a AGATCGGAAGAGCACACGTCTGAACTCCAGTCA -a AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT -m 3 -o $OUTPUTDIR/${BASENAME}_R1_001.trimmed.fastq.gz ${BASENAME}_R1_001.fastq.gz &> $OUTPUTDIR/$BASENAME
done
